# code: language=ansible
---
- name: Ensure swap file exists.
  become: true
  ansible.builtin.command: >
    dd if=/dev/zero of={{ swap_config.file }} bs=1M count={{ swap_config.size }}
  args:
    creates: '{{ swap_config.file }}'
  register: swap_file_create

- name: Set permissions on swap file.
  become: true
  ansible.builtin.file:
    path: '{{ swap_config.file }}'
    owner: root
    group: root
    mode: '0600'

- name: Make swap file if necessary.
  become: true
  ansible.builtin.command: >
    mkswap {{ swap_config.file }}
  when: swap_file_create is changed # noqa: no-handler
  changed_when: swap_file_create is changed
  register: mkswap_result

- name: Run swapon on the swap file.
  become: true
  ansible.builtin.command: >
    swapon {{ swap_config.file }}
  when: mkswap_result is changed # noqa: no-handler
  changed_when: mkswap_result is changed

# Set sysctl profiles for vm.swappiness
- name: Set sysctl vm.swappiness
  become: true
  ansible.posix.sysctl:
    name: 'vm.swappiness'
    value: '{{ swap_config.swappiness.value }}'
    sysctl_file: '{{ swap_config.swappiness.file }}'
    state: '{{ swap_config.state }}'
